format = """
$status\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$memory_usage\
$env_var\
$custom\
$sudo\
$jobs\
$cmd_duration\
$line_break\
$character"""
add_newline = false

[directory]
truncation_length = 10
truncate_to_repo = false

[sudo]
disabled = false

[status]
disabled = false
symbol = "✗"

[character]
format = " $symbol "
success_symbol = "[◢◤](bold blue)"
error_symbol = "[◢◤](bold red)"
