name: ci
on:
  push:
    branchs:
      - main

env:
  STYLUA_VERSION: 0.13.0

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare stylua
        run: curl -LO https://github.com/JohnnyMorganz/StyLua/releases/download/v${STYLUA_VERSION}/stylua-linux.zip
      - name: Execute stylua
        run: ./stylua --config-path .config/lua/stylua.toml -g '.*/' -g '*.lua' -v .
      - name: Check if there are any changes
        continue-on-error: true
        run: git diff --exit-code
      - name: Create pull request if changed
        if: failure()
        uses: peter-evans/create-pull-request@v4.0.3
        with:
          commit-message: ':rotating_light: fix: format'
