name: ci
on:
  push:
    branchs:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path .config/lua/stylua.toml -g '.*/' -g '*.lua' .
      - name: Check if there are any changes
        run: git diff --exit-code
      - name: Create pull request if changed
        if: failure()
        uses: peter-evans/create-pull-request@v4.0.3
        with:
          commit-message: ':rotating_light: fix: format'
